## Execute 'docker-compose -p qa-diploma up -d --force-recreate' --build
## to start all containers in daemon mode
## Where:
##      '-p qa-diploma' -- specifies container's prefix (project name)
##      '-d' -- enables daemon mode
##      '--force-recreate' -- forces re-recreating of all containers

version: '3.7'
services:

  gate-simulator:
    build: .
    image: gate-simulator:1.0
    ports:
      - '9999:9999'

  mysql:
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=base_mysql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgres
    environment:
      - POSTGRES_DB=base_postgresql
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass